[build]
  publish = "."
  
[[redirects]]
  from = "/projects"
  to = "/projects.html"
  status = 301

[[redirects]]
  from = "/projects/"
  to = "/projects.html"
  status = 301

[[redirects]]
  from = "/project"
  to = "/projects.html"
  status = 301

[[redirects]]
  from = "/project/"
  to = "/projects.html"
  status = 301

# Handle other common variations
[[redirects]]
  from = "/bio"
  to = "/bio.html"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 301

[[redirects]]
  from = "/log"
  to = "/log.html"
  status = 301


[build.environment]
  NODE_VERSION = "18"