[build]
  publish = "."
  
[[redirects]]
  from = "/projects"
  to = "/projects.html"
  status = 301

[[redirects]]
  from = "/project"
  to = "/projects.html"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[build.environment]
  NODE_VERSION = "18"